"""empty message

Revision ID: 103b99a70ef0
Revises: 26c49843a2c8
Create Date: 2021-06-18 10:19:17.386288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103b99a70ef0'
down_revision = '26c49843a2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('num_shows', sa.Integer(), nullable=True))
    op.drop_column('Venue', 'cs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('cs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'num_shows')
    # ### end Alembic commands ###
