"""empty message

Revision ID: 26c49843a2c8
Revises: a98d278a693c
Create Date: 2021-06-18 09:57:01.201291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c49843a2c8'
down_revision = 'a98d278a693c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('cs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'cs')
    # ### end Alembic commands ###
