"""empty message

Revision ID: 3e8f2c4596ee
Revises: 891f8315e653
Create Date: 2021-06-16 06:19:18.398929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8f2c4596ee'
down_revision = '891f8315e653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.drop_constraint('show_Venue_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'Venue', ['venue_id'], ['id'])
    op.drop_column('show', 'Venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('Venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_Venue_id_fkey', 'show', 'Venue', ['Venue_id'], ['id'])
    op.drop_column('show', 'venue_id')
    # ### end Alembic commands ###
