"""empty message

Revision ID: 494d28aabff8
Revises: 3e8f2c4596ee
Create Date: 2021-06-16 08:13:02.300755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494d28aabff8'
down_revision = '3e8f2c4596ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.Integer(), nullable=True))
    op.drop_column('show', 'StartT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('StartT', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
