"""empty message

Revision ID: a98d278a693c
Revises: ed03358df192
Create Date: 2021-06-17 09:50:21.298506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98d278a693c'
down_revision = 'ed03358df192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('Artist_id', sa.Integer(), nullable=True))
    op.drop_constraint('show_artist_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'Artist', ['Artist_id'], ['id'])
    op.drop_column('show', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_artist_id_fkey', 'show', 'Artist', ['artist_id'], ['id'])
    op.drop_column('show', 'Artist_id')
    # ### end Alembic commands ###
