"""empty message

Revision ID: af0377a9f1b1
Revises: 3afae3a067de
Create Date: 2021-06-23 12:14:15.584718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0377a9f1b1'
down_revision = '3afae3a067de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='genres_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='genres_pkey')
    )
    # ### end Alembic commands ###
