"""empty message

Revision ID: b8099e48b67f
Revises: 103b99a70ef0
Create Date: 2021-06-18 10:31:49.684813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8099e48b67f'
down_revision = '103b99a70ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_date', sa.String(), nullable=True))
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('show', 'start_date')
    # ### end Alembic commands ###
