"""empty message

Revision ID: ed03358df192
Revises: 7a82d5f059a6
Create Date: 2021-06-17 09:42:56.969724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed03358df192'
down_revision = '7a82d5f059a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.drop_constraint('show_Artist_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'Artist', ['artist_id'], ['id'])
    op.drop_column('show', 'Artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('Artist_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_Artist_id_fkey', 'show', 'Artist', ['Artist_id'], ['id'])
    op.drop_column('show', 'artist_id')
    # ### end Alembic commands ###
